### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by jlblancoc** [mrpt-ros-pkg/mrpt_sensors#1]
* [x] generic mrpt sensor lib, on which all nodes depend on
   * [X] port to ROS 2
   * [x] publish as CObservation binary
   * [ ] Publish as sensor specific msgs:
     * [x] NMEA GPS
     * [ ] pointcloud2
     * [ ] 2D scan
     * [ ] images
     * [ ] NTRIP corrections
     * [ ] NOVATEL GPS
     * [ ] NTRIP + RTK demo launch
   * [x] read sensor pose from launch file params and publish as /tf
* [x] `mrpt_generic_sensor` node
* [ ] diagnostics (?)
